server:
  port: 8080

endpoints: 
  refresh:
    sensitive: false

management:
  endpoints:
    web:
      exposure:
        include: "refresh"

spring:
  datasource:
    url: 'jdbc:mysql://mysql-monolith:3306/monolith?useSSL=false&allowPublicKeyRetrieval=true'
    driver: 'com.mysql.cj.jdbc.Driver'
    username: 'root'
    password: '123456'
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: 'org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor'
        connection:
          charSet: 'UTF-8'
        show_sql: false
    hibernate:
      cache:
        use_query_cache: false
        use_second_level_cache: false
  http:
    multipart:
      max-file-size: '1500KB'
      max-request-size: '1500KB'
  application:
    name: 'Ecommerce-starter-v1'
app:
  name: 'Ecommerce-starter'

jwt:
  header: 'Authorization'
  expires_in: '86400'
  secret: 'sgd34bwfAbfSBPpe0r8gwbg'
  
service:
  product:
    application-name: 'product-service-v1'
    products-endpoint: '/product' # should start with a slash
    product-groups-endpoint: '/group' # should start with a slash