server:
    port: 80
  
spring:
  application:
    name: 'gateway-service'
  cloud:
    gateway:
      routes:
        - id: monolith-v2
          uri: lb://ecommerce-starter-v2
          predicates:
            - Path=/cart/**,/order/**,/login
            - Header=routingKey, v2

        - id: monolith-v1 # if the routingKey header is not presented or is invalid the request will be processed by v1
          uri: lb://ecommerce-starter-v1
          predicates:
            - Path=/cart/**,/order/**,/login

        - id: product-service-v2
          uri: lb://product-service-v2
          predicates:
            - Path=/product/**,/group/**
            - Header=routingKey, v2

        - id: product-service-v1 # if the routingKey header is not presented or is invalid the request will be processed by v1
          uri: lb://product-service-v1
          predicates:
            - Path=/product/**,/group/**  