server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:mysql://mysql-product-service:3306/product_service?serverTimezone=Europe/Moscow'
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    initialization-mode: always
  mvc:
    converters:
      preferred-json-mapper: gson
  application:
    name: product-service-v1

eureka:
  instance:
    initial-status: OUT_OF_SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "refresh"